imports_granularity = "One"
tab_spaces = 2
hard_tabs = true
indent_style = "Block"
merge_derives = true
max_width = 100
newline_style = "Unix"
edition = "2021"
reorder_impl_items = true
reorder_modules = true
reorder_imports = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
imports_layout = "Vertical"
skip_children = false
format_macro_matchers = true
